# Generated by Django 4.0.4 on 2022-05-20 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('pc_global_score', models.IntegerField(default=-1)),
                ('td_global_score', models.IntegerField(default=-1)),
                ('ex_global_score', models.IntegerField(default=-1)),
                ('id_global_score', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_name', models.CharField(max_length=100)),
                ('pc_score', models.IntegerField()),
                ('pc_debrief', models.CharField(max_length=500)),
                ('td_score', models.IntegerField()),
                ('td_debrief', models.CharField(max_length=500)),
                ('ex_score', models.IntegerField()),
                ('ex_debrief', models.CharField(max_length=500)),
                ('id_score', models.IntegerField()),
                ('id_debrief', models.CharField(max_length=500)),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('interview_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.interview')),
            ],
        ),
    ]
