# Generated by Django 4.0.4 on 2022-05-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='ex_global_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='interview',
            name='id_global_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='interview',
            name='pc_global_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='interview',
            name='td_global_score',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='ex_score',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='id_score',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='pc_score',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='td_score',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
