# Generated by Django 4.0.4 on 2022-05-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_interview_ex_global_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.CharField(max_length=16),
        ),
    ]
